apiVersion: v1
kind: ConfigMap
metadata:
  name: example-cm
data:
  # SCRIPT_FILENAME is the entrypoint for the FastCGI server. This is the PHP
  # file that will be executed when a request is received.
  SCRIPT_FILENAME: "/var/www/html/index.php"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: default
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }

    http {
        server {
            listen       80;
            server_name  _;
            include       /etc/nginx/mime.types;
            root /var/www/html/;
            index index.html index.php;

            location / {
                try_files $uri /index.php$is_args$args;
            }

            location ~ \.php$ {
                include fastcgi.conf;
                fastcgi_index index.php;
                fastcgi_pass example-site:9000;
            }
        }
    }
